[project]
name = "pi0-deploy"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy<2.0",
    "pytest>=9.0.2",
]

[tool.uv]
# 使用 Dockerfile 中创建的虚拟环境
override-dependencies = []

[tool.uv.sources]
openpi = { path = "openpi" }
gello = { path = "third_party/gello_software_bp" }

[dependency-groups]
dev = [
    "gello",
    "openpi",
]
